[config]

[templates.gtk3]
input_path = "templates/gtk.css"
output_path = "~/.config/gtk-3.0/colors.css"
post_hook = "gsettings set org.gnome.desktop.interface gtk-theme ''; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}"

[templates.gtk4]
input_path = "templates/gtk.css"
output_path = "~/.config/gtk-4.0/colors.css"

[templates.hyprland]
input_path = "templates/hypr.conf"
output_path = "~/.config/hypr/colors.conf"
post_hook = "hyprctl reload"

[templates.hyprpaper]
input_path = "templates/hyprpaper.conf"
output_path = "~/.config/hypr/hyprpaper.conf"
post_hook = "systemctl --user restart hyprpaper.service"

[templates.kitty]
input_path = "templates/kitty.conf"
output_path = "~/.config/kitty/themes/material-theme.conf"
post_hook = "kitty +kitten themes --reload-in=all material-theme"

[templates.qt5ct]
input_path = "templates/qt.conf"
output_path = "~/.config/qt5ct/colors/material.conf"

[templates.qt6ct]
input_path = "templates/qt.conf"
output_path = "~/.config/qt6ct/colors/material.conf"

[templates.vesktop]
input_path = "templates/discord.css"
output_path = "~/.config/vesktop/themes/dynamic.css"

[templates.zed]
input_path = "templates/zed.json"
output_path = "~/.config/zed/themes/matugen.json"
