[config]

[templates.hyprland]
input_path = "templates/hypr.conf"
output_path = "~/.config/hypr/colors.conf"
post_hook = "hyprctl reload"

[templates.hyprpaper]
input_path = "templates/hyprpaper.conf"
output_path = "~/.config/hypr/hyprpaper.conf"
post_hook = "systemctl --user restart hyprpaper.service"

[templates.kitty]
input_path = "templates/kitty.conf"
output_path = "~/.config/kitty/themes/material-theme.conf"
post_hook = "kitty +kitten themes --reload-in=all material-theme"

[templates.vesktop]
input_path = "templates/discord.css"
output_path = "~/.config/vesktop/themes/dynamic.css"
